remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title: "Jesús de la Fuente Cedeño"

author:
  name: "Jesús de la Fuente Cedeño"
  avatar: "/assets/images/profile.jpeg" # Ensure your image is correctly uploaded
  bio: "Ph.D. in Machine Learning and Computational Biology. Trading enthusiast!"
  location: "Pamplona, Spain"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:a904346@alumni.unav.es"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jesusdfc"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jfctelecomm/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=uXbuO-sAAAAJ&hl=en"
    - label: "Kaggle"
      icon: "fab fa-fw fa-kaggle"
      url: "https://www.kaggle.com/jdlfuentec"



defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

# Sidebar settings
author_profile: true

assets:
  css: 
    - "assets/css/main.scss"

include:
  - _pages

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed

header_scripts:
  - "<link rel='icon' href='assets/images/favicon.ico' type='image/x-icon'>"